name: C/C++ CI

on:
  push:
    branches: [ version-1 ]
  pull_request:
    branches: [ version-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
